modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"
issueTrackerURL = "https://github.com/StrikerRockers-Mods/SBM-Magic-Mirror/issues "
displayURL = "https://www.curseforge.com/minecraft/mc-mods/sbm-magic-mirror/"
authors = "StrikerRocker,DarkCow"

[[mods]]
modId = "sbmmagicmirror"
version = "${file.jarVersion}"
displayName = "SBM-Magic-Mirror"
description = '''Mirror like object that is used to quickly get to the surface after exploring dungeons. '''

[[dependencies.sbmmagicmirror]] #optional
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sbmmagicmirror]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"