name: "Build Release"
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@v2, with: { fetch-depth: 0 } }
      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with: { distribution: "temurin", java-version: "17" }
      - uses: burrunan/gradle-cache-action@v1
        name: Build with Gradle
        id: build
        with:
          arguments: "setupGithubActions build"
          gradle-version: "wrapper"
      - name: "Create a Release"
        id: create_release
        uses: meeDamian/github-release@2.0
        with:
          files: "build/libs/${{ steps.build.outputs.mod_name }}-${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}.jar"
          gzip: false
          name: "${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Publish-Forge"
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 250881
          curseforge-token: ${{ secrets.CF_API_TOKEN }}
          modrinth-id: zvXcZYaA
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: forge
          version: ${{ steps.build.outputs.version }}
          files: "build/libs/${{ steps.build.outputs.mod_name }}-${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}.jar"
          name: "${{ steps.build.outputs.mod_name }}-${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}.jar"
      - name: "Build Success"
        id: build-success
        uses: itsmeow/webhook-action@master
        env:
          WEBHOOK_URL: "${{ secrets.DISCORD_WEBHOOK_URL }}"
          data: '{"embeds":[{"title":"${{ steps.build.outputs.mod_name }} Release Build","url":"https://github.com/${{ github.repository }}/releases/tag/${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}","description":"Tag: ${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}\nStatus: Successful","color":65280,"author":{"name":"${{ github.event.user.login }}","url":"${{ github.event.user.html_url }}","icon_url":"${{ github.event.user.avatar_url }}"}}]}'
      - name: "Build Fail"
        id: build-fail
        uses: itsmeow/webhook-action@master
        if: failure()
        env:
          WEBHOOK_URL: '${{ secrets.DISCORD_WEBHOOK_URL }}\'
          data: '{"embeds":[{"title":"${{ steps.build.outputs.mod_name }} Release Build","url":"https://github.com/${{ github.repository }}/releases/tag/${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}","description":"Tag: ${{ steps.build.outputs.minecraft_version }}-${{ steps.build.outputs.version }}\nStatus: Failed","color":16711680,"author":{"name":"${{ github.event.user.login }}","url":"${{ github.event.user.html_url }}","icon_url":"${{ github.event.user.avatar_url }}"}}]}'