name: Java CI
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: "Build"
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build --max-workers 1
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true